### ISSUE TITLE
Draw on a 3D surface

### ISSUE THREAD

**Issue by camroo29** [StereoKit/StereoKit-PaintTutorial#7]
Hi Nick,

I am trying to add some features to the StereoKit Paint App. One of the features I struggle to implement is drawing on a 3D surface. Rather than drawing on arbitrary space, I want to confine the drawing to only a 3D model surface (e.g. drawing on a cube surface only). 

But I am kinda clueless about how to confine my drawing only on a 3D model surface. If you have any ideas that would be really helpful.

Thanks

**Comment by maluoi** [comment]
For a flat plane, that's not too hard, you can just intersect/raycast against the plane when your fingers are close to it! For a Model/Mesh, you might be able to get away with something similar, but I expect in practice that'll have all sorts of pitfalls to it, like following the contour of the model properly. For a cube, it'd be quite tricky going around significant corners.

You're definitely tackling a tricky bit of functionality there, so if that snippet of info is not helpful for you, you may want to try re-framing your project to take on an easier problem?

**Comment by camroo29** [comment]
I guess I need to find easier problems. Thanks
